import { NextRequest, NextResponse } from 'next/server'
import sharp from 'sharp'

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { 
      canvas, // Fabric.js canvas JSON
      format = 'png', // png, jpg, jpeg
      width = 1080,
      height = 1080,
      quality = 95,
      dpi = 300 // for print quality
    } = body

    if (!canvas) {
      return NextResponse.json(
        { error: 'Canvas data is required' },
        { status: 400 }
      )
    }

    // For MVP, we'll generate a simple placeholder image
    // In the full implementation, this would:
    // 1. Parse the Fabric.js canvas JSON
    // 2. Render text, images, shapes, etc.
    // 3. Apply templates and layouts
    // 4. Generate the final image

    // Create a placeholder image with text
    const svg = `
      <svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg">
        <defs>
          <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
            <stop offset="0%" style="stop-color:#3B82F6;stop-opacity:1" />
            <stop offset="100%" style="stop-color:#1E40AF;stop-opacity:1" />
          </linearGradient>
        </defs>
        <rect width="100%" height="100%" fill="url(#bg)"/>
        <rect x="40" y="40" width="${width-80}" height="${height-80}" fill="white" rx="20" opacity="0.95"/>
        <text x="${width/2}" y="200" font-family="Arial, sans-serif" font-size="48" font-weight="bold" text-anchor="middle" fill="#1E40AF">
          Spyglass Studio
        </text>
        <text x="${width/2}" y="260" font-family="Arial, sans-serif" font-size="24" text-anchor="middle" fill="#6B7280">
          Marketing Image Export
        </text>
        <text x="${width/2}" y="320" font-family="Arial, sans-serif" font-size="18" text-anchor="middle" fill="#6B7280">
          ${width}x${height} • ${format.toUpperCase()} • ${dpi} DPI
        </text>
        <text x="${width/2}" y="${height-100}" font-family="Arial, sans-serif" font-size="16" text-anchor="middle" fill="#9CA3AF">
          Generated by Spyglass Studio API
        </text>
      </svg>
    `

    // Convert SVG to image using Sharp
    let imageBuffer = await sharp(Buffer.from(svg))
      .png()
      .toBuffer()

    // Apply format conversion
    if (format === 'jpg' || format === 'jpeg') {
      imageBuffer = await sharp(imageBuffer)
        .jpeg({ quality })
        .toBuffer()
    }

    // Set appropriate headers
    const contentType = format === 'png' ? 'image/png' : 'image/jpeg'
    const filename = `spyglass-studio-export.${format}`

    return new NextResponse(imageBuffer, {
      headers: {
        'Content-Type': contentType,
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Content-Length': imageBuffer.length.toString(),
      },
    })

  } catch (error) {
    console.error('Error exporting image:', error)
    return NextResponse.json(
      { error: 'Failed to export image' },
      { status: 500 }
    )
  }
}

// GET endpoint for testing
export async function GET() {
  return NextResponse.json({
    endpoint: 'Image Export API',
    description: 'POST canvas data to generate marketing images',
    supported_formats: ['png', 'jpg', 'jpeg'],
    max_dimensions: { width: 4000, height: 4000 },
    example: {
      canvas: { /* Fabric.js canvas JSON */ },
      format: 'png',
      width: 1080,
      height: 1080,
      quality: 95,
      dpi: 300
    }
  })
}