#!/bin/bash

echo "📧 Attorney Email Package Ready!"
echo "================================"
echo ""
echo "Files to attach:"
echo "✅ attorney-master-list.csv (21 attorneys with contact info)"
echo "✅ email-report.md (executive summary)"
echo "✅ dashboard-design.html (visual project tracker)"
echo ""
echo "Recipients: ryan@spyglassrealty.com, sunny@spyglassrealty.com"
echo ""
echo "Email body is in: email-body.txt"
echo ""
echo "To send manually:"
echo "1. Open Gmail"
echo "2. Copy content from email-body.txt"
echo "3. Attach the 3 files listed above"
echo "4. Send to both recipients"
echo ""
echo "All files are in: $(pwd)"