#!/usr/bin/env tsx
/**
 * Seed pulse_community_allowlist from the live spyglassrealty.com/communities county tabs.
 * Source: county tab scrape, 2026-04.
 *
 * Matching rules:
 *   - Exact: case-insensitive communities.name match, scoped to the expected county
 *   - Fuzzy fallback (not auto-inserted): normalized whitespace + punctuation stripped
 *
 * Run:
 *   npx tsx scripts/seed-pulse-allowlist.ts --dry-run
 *   npx tsx scripts/seed-pulse-allowlist.ts
 */

import { db } from '../server/db';
import { communities, pulseCommunityAllowlist } from '@shared/schema';
import { sql, ilike, and, count } from 'drizzle-orm';

const DRY_RUN = process.argv.includes('--dry-run');

// ---------------------------------------------------------------------------
// Authoritative name lists from the live site county tabs (do not modify).
// Travis County (315)
// ---------------------------------------------------------------------------
const TRAVIS_NAMES: string[] = [
  "04 Lofts",
  "Allandale",
  "Anderson Mill",
  "Anderson Mill West",
  "Angel Bay",
  "Angelwylde",
  "Apache Shores",
  "Arbolago",
  "Armstrong Point",
  "Arrowhead Point",
  "Ashley Oaks",
  "Austin Lake Estates",
  "Austin Proper Residences",
  "Autumn Wood",
  "Barton Creek",
  "Barton Creek Ranch",
  "Barton Creek West",
  "Barton Hills",
  "Barton Valley",
  "Beby's Ranch",
  "Bee Caves West",
  "Bee Creek Ranchettes",
  "Bee Creek Terrace",
  "Bell Springs Ranches",
  "Bella Colinas",
  "Bella Vista",
  "Bella Vista At Cottonwood Creek",
  "Belvedere",
  "Big Country",
  "Blackland",
  "Bluebonnet Acres",
  "Bouldin",
  "Boulevard at Lakeway",
  "Breakaway Park",
  "Brentwood",
  "Brookfield Estates",
  "Brookhollow",
  "Brooks Hollow",
  "Bruton Springs",
  "Bryker Woods",
  "Buffalo Gap",
  "Bunker Ranch",
  "Burger Ridge Estates",
  "Cambridge Heights",
  "Cantarra",
  "Cardinal Hills Estates",
  "Carol Oaks",
  "Carriage Hills",
  "Cedar Ridge Estates",
  "Cedar Springs Ranch",
  "Central East Austin",
  "Cherry Creek",
  "Cherrywood",
  "Chestnut",
  "Chestnut Ridge",
  "Clarksville",
  "Cluck Creek Estates",
  "Colonia Serendipity",
  "Copperfield",
  "Coronado Hills",
  "Cortona",
  "Costa Bella",
  "Coves at Sky Ranch",
  "Coves on Lake Travis",
  "Creekview",
  "Crestview",
  "Crossroads Estates",
  "Cypress Acres",
  "Cypress Mill",
  "Davenport Ranch",
  "Dawson",
  "Decker Lake",
  "Deer Haven",
  "Deerfield Estates",
  "Del Valle",
  "Dittmar-Slaughter",
  "Douglas Estates",
  "Dove Creek",
  "Downtown",
  "Downtown Austin",
  "East Austin",
  "East Cesar Chavez",
  "East Congress",
  "East Oak Hill",
  "Eck Lane on the Lake",
  "Edgewater Beach",
  "Emerald Point",
  "Estates At Blackacre",
  "Estates at Settlers Park",
  "Estates of Lewis Mountain",
  "Falconhead",
  "Fitzhugh Corners",
  "Fitzhugh Place",
  "Flintrock Falls",
  "Flower Hill",
  "Forest Oaks",
  "Forest Ridge",
  "Fort Dessau",
  "Founders Ridge",
  "Fox Creek Estates",
  "Franklin Park",
  "Galindo",
  "Garrison Park",
  "Gateway",
  "Geneva Estates",
  "Georgian Acres",
  "Glen-Ledge Park",
  "Glenwood",
  "Govalle",
  "Gracywoods",
  "Granada Estates",
  "Green Acres",
  "Greenridge",
  "Greenshores",
  "Hamilton Hills",
  "Hammett's Crossing",
  "Hancock",
  "Harmon Hills",
  "Harris Branch",
  "Harris Ridge",
  "Harrison Hills",
  "Hays Wartha",
  "Hazy Hills Ranchettes",
  "Heather Hills",
  "Heritage Country",
  "Heritage Hills",
  "Heritage Oaks",
  "Heritage West",
  "Hidden Creek",
  "Hidden Springs Ranch",
  "Highland",
  "Highland Club Village",
  "Highland Lake Estates",
  "Highland Oaks",
  "Highland Park",
  "Hill Country Estates",
  "Hill Creek West",
  "Hillview",
  "Holly",
  "Honeycomb Hills",
  "Hyde Park",
  "Indian Point",
  "Jester",
  "Jester Farms",
  "Johnston Terrace",
  "La Hacienda Estates",
  "La Tierra De Los Pedernales",
  "Ladera",
  "Laguna Vista",
  "Lake Pointe",
  "Lake Ridge Estates",
  "Lakehurst",
  "Lakeview Gardens",
  "Lakewind Estates",
  "Ledge Stone",
  "Lick Creek Ranch",
  "Liveoak Terrace",
  "Lodge Acres",
  "Loma Vista",
  "Long Branch Valley",
  "Longview",
  "Los Rincones",
  "Madrone Canyon Ranch",
  "Madrone Ranch",
  "Majestic Hills Ranchettes",
  "Mayfield Ranch",
  "McNeil",
  "Meadowfox Estates",
  "Mission Oaks",
  "MLK",
  "Montopolis",
  "Mountain Oaks",
  "Mountain View",
  "Mountaintop Acres",
  "Mueller",
  "Mystic Creek",
  "Naumann's Camp",
  "Noack Hill",
  "North Austin",
  "North Burnett",
  "North Forty",
  "North Lamar",
  "North Loop",
  "North Park",
  "North Rim",
  "North Shoal Creek",
  "North University",
  "Northridge",
  "Northtown",
  "Northwest Hills",
  "Oak Forest",
  "Oak Hollow",
  "Oak Run Estates",
  "Oak Run West",
  "Oakmont Heights",
  "Old Enfield",
  "Old Ferry",
  "Old Town",
  "Onion Creek",
  "Overlook at Lewis Mountain",
  "Paleface Homesteads",
  "Paleface Lake Country Estates",
  "Paleface Park",
  "Paleface Pedernales",
  "Paleface Ranch",
  "Palomino Ridge",
  "Papoose",
  "Parker Lane",
  "Pauls Valley",
  "Pecan Springs Springdale",
  "Pedernales Canyon Ranch",
  "Pemberton Heights",
  "Pioneer Hill",
  "Pleasant Valley",
  "Point Pedernales",
  "Poole Place",
  "Rawhide Ridge",
  "Red Bud Hills",
  "Remington Heights",
  "Rob Roy",
  "Ryans Crossing",
  "Saddletree Ranch",
  "Sage Creek",
  "Senna Hills",
  "Shadow Oaks",
  "Shady Valley",
  "Silverado Estates",
  "Skyline Terrace",
  "Slaughter Creek",
  "Slaughter Creek Acres",
  "Sleepy Hollow",
  "South Lake Travis",
  "South Austin",
  "South Brodie",
  "South Lamar",
  "South Manchaca",
  "Southwest Territory",
  "Spring Creek Estates",
  "Spring Trails",
  "Springbrook",
  "Springlake",
  "St. Edwards",
  "St. Johns",
  "Stagecoach Ranch",
  "Steiner Ranch",
  "Stonegate",
  "Stonehedge Estates",
  "Sunny Ridge",
  "Sunrise Country",
  "Sunset Canyon",
  "Sunset Oaks",
  "Sweet Briar",
  "Sycamore Creek",
  "Sycamore Valley",
  "Tanglewood West",
  "Tarrytown",
  "The Austonian",
  "The Boondocks",
  "The Estates Above Lost Creek",
  "The Hills of Lost Creek",
  "The Homestead",
  "The Overlook",
  "The Preserve at Barton Creek",
  "The Ridge at Alta Vista",
  "The Springs",
  "The Trails",
  "The Uplands",
  "The Woodlands",
  "The Woods",
  "The Woods of Lake Travis",
  "Thurman Bend Estates",
  "Tiburon Hills",
  "Tierra Vista",
  "Travis Bluff",
  "Travis Country",
  "Travis Heights",
  "Travis Landing",
  "Travis Oaks",
  "Travis Settlement",
  "Triangle State",
  "Triple Creek Ranch",
  "Two Creeks",
  "University Hills",
  "University of Texas",
  "Valley Oak",
  "Village at Western Oaks",
  "Vineyard Bay",
  "Vista Grande",
  "Vista West",
  "Walking W Ranch",
  "Waterstone",
  "West Cave Estates",
  "West Congress",
  "West Cypress Hills",
  "West Oak Hill",
  "West University",
  "Westgate",
  "Westlake",
  "Westlake Oaks",
  "Westlake Terrace",
  "Westover Hills",
  "Westridge Estates",
  "Westwind",
  "Westwood",
  "Wild Plum Valley",
  "Windmill Bluff Estates",
  "Windsong Estates",
  "Windsor Hills",
  "Wood Trail Estates",
  "Wooten",
  "Wren Valley",
  "Wynnrock Estates",
  "Yacht Harbor",
  "Yaupon Creek",
  "Zilker",
];

// Williamson County (325)
const WILLIAMSON_NAMES: string[] = [
  "Abrantes",
  "Air Country Estates",
  "Apache Oaks",
  "Apple Springs",
  "Arbor Place",
  "Ashton Oaks",
  "Avery Ranch",
  "Barton Creek Lakeside",
  "Behrens Ranch",
  "Bell Meadows",
  "Bellview",
  "Beltorre",
  "Benbrook Ranch",
  "Bent Tree",
  "Berry Creek",
  "Block House Creek",
  "Bradford Park",
  "Brangus Ranch",
  "Briarwood",
  "Brookchase",
  "Brookside",
  "Brushy Bend Park",
  "Brushy Creek Meadows",
  "Brushy Creek North",
  "Brushy Point Estates",
  "Brushy Slope",
  "Bryson",
  "Buttercup Creek",
  "Caballo Ranch",
  "Candle Oaks",
  "Carmel Creek Estates",
  "Carneros Ranch",
  "Carol Meadows",
  "Casa Loma River Oaks",
  "Cat Hollow",
  "Cedar Hollow Crossing",
  "Cedar Park Square",
  "Chandler Creek",
  "Chaparro Estates",
  "Chapel Hill North",
  "Cherry Hollow Estates",
  "Chisholm Crossing",
  "Chisholm Park",
  "Chisholm Valley",
  "Chisholm Valley West",
  "Churchill Farms",
  "Cimarron Hills",
  "Clarks Crossing",
  "Coffee",
  "Cold Springs",
  "Concord At Brushy Creek",
  "Connellys Crossing",
  "Country Club Estates",
  "Country West",
  "County Glen",
  "Coventry Crossing",
  "Creek Bend",
  "Creekside",
  "Creekside Estates",
  "Cross Country Estates",
  "Cross Creek",
  "Crossing at Carriage Hills",
  "Crystal Crossing",
  "Crystal Falls",
  "Cushing Park",
  "Cypress Bend",
  "Cypress Canyon",
  "Cypress Creek",
  "Deerbrooke",
  "Deerfield Park",
  "Deerfield Village",
  "Diamond Oaks",
  "Donnell Parke",
  "Downtown Georgetown",
  "Eagle Ridge",
  "East Lynn",
  "East Main",
  "Emerald Oaks",
  "Emory Farms",
  "Enclave At Brushy Creek",
  "Escalera Ranch",
  "Eubank",
  "Falcon Oaks",
  "Falls of San Gabriel",
  "Family Acres",
  "Fern Bluff",
  "Forest Bluff",
  "Forest Creek",
  "Forest Creek Estates",
  "Forest Grove",
  "Forest North Estates",
  "Fountainwood",
  "Gabriel Estates",
  "Gabriel Farms",
  "Gabriel Heights",
  "Gabriels Grove",
  "Gabriels Overlook",
  "Gann Ranch",
  "Garden Park",
  "Gardens At Verde Vista",
  "Georgetown Crossing",
  "Georgetown Place",
  "Georgetown Village",
  "Georgian Place",
  "Giles Estates",
  "Glazier Ranch",
  "Glenwood Park",
  "Golden Oaks",
  "Grayson",
  "Great Oaks",
  "Great Oaks Estates",
  "Greatwood",
  "Green Haven Ranch",
  "Greenfield",
  "Greengate",
  "Greenhill",
  "Greenlawn Place",
  "Greenlawn Village",
  "Greenslopes at Lake Creek",
  "Hawes Ranch",
  "Hawkes Landing",
  "Hazlewood",
  "Heritage On San Gabriel",
  "Heritage Park",
  "Hernandos Hideaway",
  "Hidden Acres",
  "Hidden Glen",
  "Hidden Mesa",
  "High Chaparral",
  "High Country",
  "High Gabriel East",
  "High Gabriel West",
  "High Hat Mountain",
  "High Meadows",
  "Highcrest Meadow",
  "Highland Horizon",
  "Highland Park North",
  "Highland South",
  "Highlands at Mayfield Ranch",
  "Highway Village",
  "Horizon Park",
  "Hutto Highlands",
  "Hutto Square",
  "Huttoparke",
  "Indian Creek",
  "Indian Springs",
  "Katy Cove Estates",
  "Katy Crossing",
  "Kensington Place",
  "Lakecliff on Lake Travis",
  "Lakeline Oaks",
  "Lakeside",
  "Lakewood Country Estates",
  "Lakewood Estates",
  "Larkspur",
  "Leander Crossing",
  "Leander Hills",
  "Ledbetter Oaks",
  "Legend Oaks",
  "Legends Village",
  "Little Oaks",
  "Live Oak Park",
  "Logan Plateau",
  "Lookout At Brushy Creek",
  "Meadows Of Georgetown",
  "Mesa Ridge",
  "Morningside Estates",
  "Morningside Meadows",
  "Morningstar",
  "North Creek",
  "North Georgetown",
  "North Lake",
  "Northfields",
  "Northlake Hills",
  "Northside Meadows",
  "Northwood Oaks",
  "Oak Bluff Estates",
  "Oak Brook",
  "Oak Creek",
  "Oak Ridge",
  "Oakcreek",
  "Oakmont Forest",
  "Oaks At San Gabriel",
  "Oaks at Wildwood",
  "Oakwood Glen",
  "Old Mill Village",
  "Old Oak Estates",
  "Old Town Meadows",
  "Old Town Village",
  "Olde Oak Estates",
  "Orchard Ridge",
  "Overlook Estates",
  "Palmera Ridge",
  "Paloma Lake",
  "Panoramic Hills",
  "Park at Brushy Creek",
  "Park Place",
  "Parkside at Mayfield Ranch",
  "Parkview Estates",
  "Parkwest Estates",
  "Peach Tree Valley",
  "Pecan Branch",
  "Pecan Creek",
  "Pecan Hills",
  "Pennington Place",
  "Pflugerville Acres",
  "Pflugerville Heights",
  "Pinnacle",
  "Pioneer Crossing",
  "Raintree",
  "Ranch at Brushy Creek",
  "Ranch at Cypress Creek",
  "Rancho Sienna",
  "Red Wagon Ranchettes",
  "River Chase",
  "Rivers Crossing",
  "Riviera Springs",
  "Rocky Hollow Estates",
  "Rolling Hills",
  "Rolling Meadows",
  "Round Mountain Oaks",
  "Sanaloma Estates",
  "Santa Rita Ranch",
  "Sendero Springs",
  "Settlers Overlook",
  "Shadow Pointe",
  "Shady Mountain",
  "Shenandoah",
  "Sierra Vista",
  "Silver Leaf",
  "Smith Branch Park",
  "Snow Woods",
  "Somerset",
  "Somerville",
  "Sonoma",
  "South Creek",
  "South Park",
  "South San Gabriel",
  "South San Gabriel Ranches",
  "Southern Hills",
  "Southern Terrace",
  "Southside",
  "Southside Acres",
  "Spanish Oak Springs",
  "Spanish Oak Terrace",
  "Spanish Oaks",
  "Spring Ridge",
  "Springbrook Centre",
  "Springbrook Enclave",
  "Springbrook Glen",
  "Star Ranch",
  "Stewart Crossing",
  "Stone Canyon",
  "Stone Oak",
  "Stonehedge",
  "Stonehurst",
  "Stoney Brook",
  "Summerlyn",
  "Summit At Round Rock",
  "Sun City",
  "Sunny Acres",
  "Sunrise Villas",
  "Sunrise Vista",
  "Sunset Ranchettes",
  "Sunset Ridge",
  "Teravista",
  "Texas Traditions",
  "The Bluffs",
  "The Brownstone at the Summit",
  "The Crossing",
  "The Hollows",
  "The Oaklands",
  "The Place",
  "The Pointe",
  "The Preserve",
  "Thomison",
  "Thousand Oaks",
  "Timberline West",
  "Tonkawa Springs",
  "Tonkawa Village",
  "Tonkowan Country",
  "Trails End at Lake Travis",
  "Travisso",
  "Trinity Place",
  "Turtle Bend",
  "Turtle Creek Village",
  "Twin Creek Hollow",
  "Twin Creeks",
  "Twin Ridge",
  "Twin Springs",
  "University Park",
  "University Terrace",
  "Valle Verde Beach",
  "Valley View",
  "Valley Vista",
  "Village at Mayfield Ranch",
  "Village Oaks",
  "Vineyard at Block House Creek",
  "Vista Oaks",
  "Vista Ridge Estates",
  "Vizcaya",
  "Wade Crossing",
  "Walburg Crossing",
  "Walsh Ranch",
  "West Park Estates",
  "West Park Oaks",
  "Westview Meadows",
  "Whisper Wood",
  "White Rim Mountain",
  "White Rock Estates",
  "Whitestone Landing",
  "Whitestone Oaks",
  "Whitetail",
  "Wilderness Estates",
  "Wildwood",
  "Windy Terrace",
  "Wolf Ranch",
  "Wood Glen",
  "Wood Ranch",
  "Woodland Park",
  "Woods at Crystal Falls",
  "Woods at Mason Creek",
  "Woods of Brushy Creek",
  "Young Ranch",
  "Zunker Meadows",
];

// Hays County (208)
const HAYS_NAMES: string[] = [
  "Allegre Monantial",
  "Amberwood",
  "Anderson Acres",
  "Angel Hill",
  "Anthem",
  "Appaloosa Acres",
  "Appaloosa Run",
  "Apple Valley Mobile Estates",
  "Arrow Lake Acres",
  "Arrowhead Ranch",
  "Arroyo Ranch",
  "Ashford Park",
  "Backus Estates",
  "Bear Creek Estates",
  "Bear Creek Oaks",
  "Bella Vita",
  "Belterra",
  "Blanco Bend",
  "Blanco Gardens",
  "Blanco River Estates",
  "Blanco River North",
  "Blanco Vista",
  "Blue Creek Ranch",
  "Blue Ridge",
  "Blue Sky Ranch",
  "Bluebonnet Estates",
  "Bonita Vista",
  "Bradfield Village",
  "Branch View",
  "Brooks Crossing",
  "Butler Ranch Estates",
  "Caliterra",
  "Castle Forest",
  "Cedar Hollow",
  "Cedar Springs",
  "Chama Trace",
  "Chaparral Park",
  "Cimarron Park",
  "Circle N Ranch",
  "Cliffside Wimberley",
  "Collins Heights",
  "Constellation",
  "Copper Hills",
  "Cottonwood Creek",
  "Cottonwood Hollow",
  "Country Estates",
  "Country Ridge",
  "Coves of Cimarron",
  "Creek Of Driftwood",
  "Creek Road Ranch",
  "Creekside Village",
  "Crestview Ranch",
  "Cross Valley",
  "Crosswinds",
  "Cullen Country",
  "Cypress Creek Acres",
  "Cypress Fairway Village",
  "Cypress Forest",
  "Deer Lake Estates",
  "Deer Run Estates",
  "Deerwood Estates",
  "Dos Lagos",
  "Dove Hollow Estates",
  "Dove Meadow",
  "Dove Springs",
  "Driftwood Falls Estates",
  "Dripping Springs Heights",
  "Dripping Springs Ranch",
  "Dunbar",
  "East Guadalupe",
  "El Camino Real",
  "Elm Grove",
  "Fairlawn",
  "Fieldstone",
  "Fischer Cove",
  "Flite Acres Little Ranches",
  "Forest Hills",
  "Forest Woods",
  "Four Seasons Farm",
  "Fox Ridge",
  "Fox Run Estates",
  "Friendship Ranch",
  "Garlic Creek",
  "Goforth Village",
  "Goldenwood",
  "Great Hills",
  "Green Haven Estates",
  "Green Hills",
  "Green Meadows",
  "Green Pastures",
  "Hays Country Acres",
  "Hays Country Oaks",
  "Heritage",
  "Heritage Hill",
  "Hidden Valley Estates",
  "Highpointe",
  "Hill Country Ranches",
  "Hillcroft",
  "Hills Of Hays",
  "Hillside Terrace",
  "Hilltop Place",
  "Holland Hills",
  "Homesteads At Gatlin Creek",
  "Hughson Heights",
  "Hunter Ridge",
  "Huntington Estates",
  "Indian Paintbrush",
  "Inwood Forest West",
  "Kimbro",
  "Kingsway",
  "Kingswood",
  "La Ventana",
  "La Vista",
  "Lanier Ranch",
  "Las Lomas",
  "Lea Acres",
  "Leisurewoods",
  "Liberty Ranch",
  "Los Ranchos",
  "Mccarty Ranch",
  "Meadow Vista",
  "Meadow Woods",
  "Meadows Of Kyle",
  "Millview East",
  "Morningwood",
  "Mountain City Oaks",
  "Mountain Crest",
  "Nester Estates",
  "Oak Heights",
  "Oak Meadows",
  "Oak Ridge Estates",
  "Oak Springs",
  "Onion Creek Ranch",
  "Otis Eels",
  "Oxbow Trails",
  "Panther Creek",
  "Paradise Hills",
  "Paradise Valley",
  "Peabody Place",
  "Plum Creek",
  "Posey Road Ranch Estates",
  "Presidio Alma",
  "Rabbit Hill",
  "Radiance",
  "Riverledge Estate",
  "Rolling Oaks",
  "Rutherford West",
  "Sawyer Ranch",
  "Shadow Valley",
  "Shady Grove",
  "Sierra Circle",
  "Sierra West",
  "Silver Spur Ranchettes",
  "Silverstone",
  "Six Pines",
  "Skyline Ranch Estates",
  "Smokey Mountain Oaks",
  "South Grove",
  "South Ranches",
  "South River",
  "Southern Woods",
  "Southlake Ranch",
  "Southwest Hills",
  "Spoke Hill",
  "Spring Branch",
  "Spring Hollow",
  "Spring Lake Hills",
  "Springwood",
  "Steeplechase",
  "Stone Ridge",
  "Stonefield",
  "Stonewood Commons",
  "Studio Estates",
  "Summer Mountain Ranch",
  "Summer Pointe",
  "Summer Sun",
  "Sunfield",
  "Sunrise Acres",
  "Sunset Acres",
  "Sunset Hills",
  "Syphrett Estates",
  "Tanglewood",
  "Texas Heritage Village",
  "The Farms",
  "The Highlands",
  "The Hills Of Texas",
  "The Oaks",
  "The Settlement",
  "Timmeron",
  "Turkey Hollow",
  "Twin Mountain Manor",
  "Two Rivers East",
  "Victory Gardens",
  "Viewpoint Estates",
  "Village West",
  "Vineyard Ridge",
  "Wagon Wheel",
  "Waterleaf",
  "White Oak Preserve",
  "Wildwood Hills",
  "Willow Creek",
  "Wimberley Hills",
  "Wimberley Oaks",
  "Windridge",
  "Woodland Estates",
  "Woodlands Park",
  "York Creek Meadows",
  "York Creek Ranch",
];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function normalize(s: string): string {
  return s
    .toLowerCase()
    .replace(/[\s\-\.\']+/g, ' ')
    .trim();
}

interface MatchResult {
  sourceName: string;
  county: string;
  slug: string | null;
  dbName: string | null;
  type: 'exact' | 'fuzzy' | 'missing';
  fuzzyCandidate?: { slug: string; dbName: string };
}

async function processCounty(
  names: string[],
  county: string,
): Promise<MatchResult[]> {
  // Pull all communities rows for this county (case-insensitive)
  const rows = await db
    .select({ slug: communities.slug, name: communities.name })
    .from(communities)
    .where(sql`LOWER(${communities.county}) = LOWER(${county})`);

  const byLowerName = new Map<string, { slug: string; name: string }>();
  const byNormName = new Map<string, { slug: string; name: string }>();
  for (const row of rows) {
    byLowerName.set(row.name.toLowerCase(), row);
    byNormName.set(normalize(row.name), row);
  }

  const results: MatchResult[] = [];

  for (const sourceName of names) {
    const lowerSource = sourceName.toLowerCase();
    const normSource = normalize(sourceName);

    const exactRow = byLowerName.get(lowerSource);
    if (exactRow) {
      results.push({ sourceName, county, slug: exactRow.slug, dbName: exactRow.name, type: 'exact' });
      continue;
    }

    // Fuzzy fallback
    const fuzzyRow = byNormName.get(normSource);
    if (fuzzyRow) {
      results.push({
        sourceName,
        county,
        slug: null,
        dbName: null,
        type: 'fuzzy',
        fuzzyCandidate: { slug: fuzzyRow.slug, dbName: fuzzyRow.name },
      });
      continue;
    }

    results.push({ sourceName, county, slug: null, dbName: null, type: 'missing' });
  }

  return results;
}

async function getExistingCounts(): Promise<Record<string, number>> {
  const rows = await db
    .select({ county: pulseCommunityAllowlist.county, cnt: count() })
    .from(pulseCommunityAllowlist)
    .groupBy(pulseCommunityAllowlist.county);
  const out: Record<string, number> = {};
  for (const r of rows) out[r.county] = Number(r.cnt);
  return out;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  console.log(`\n=== seed-pulse-allowlist ${DRY_RUN ? '[DRY RUN]' : '[LIVE]'} ===\n`);

  const countyMap: Array<{ county: string; names: string[] }> = [
    { county: 'Travis', names: TRAVIS_NAMES },
    { county: 'Williamson', names: WILLIAMSON_NAMES },
    { county: 'Hays', names: HAYS_NAMES },
  ];

  const allResults: MatchResult[] = [];

  for (const { county, names } of countyMap) {
    const results = await processCounty(names, county);
    allResults.push(...results);
  }

  const exact = allResults.filter(r => r.type === 'exact');
  const fuzzy = allResults.filter(r => r.type === 'fuzzy');
  const missing = allResults.filter(r => r.type === 'missing');

  // Insert exact matches
  if (!DRY_RUN && exact.length > 0) {
    const rows = exact.map(r => ({
      slug: r.slug!,
      county: r.county,
    }));
    await db
      .insert(pulseCommunityAllowlist)
      .values(rows)
      .onConflictDoNothing();
  }

  // ---------------------------------------------------------------------------
  // Report
  // ---------------------------------------------------------------------------

  if (fuzzy.length > 0) {
    console.log('--- FUZZY MATCH CANDIDATES (not inserted — review required) ---');
    for (const r of fuzzy) {
      console.log(
        `  [${r.county}] "${r.sourceName}"  →  db: "${r.fuzzyCandidate!.dbName}" (slug: ${r.fuzzyCandidate!.slug})`,
      );
    }
    console.log();
  }

  if (missing.length > 0) {
    console.log('--- MISSING (no match found) ---');
    for (const r of missing) {
      console.log(`  [${r.county}] "${r.sourceName}"`);
    }
    console.log();
  }

  const existingCounts = await getExistingCounts();
  const totalExisting = Object.values(existingCounts).reduce((a, b) => a + b, 0);

  console.log('--- SUMMARY ---');
  console.log(`Exact matches: ${exact.length} (${DRY_RUN ? 'would insert' : 'inserted'})`);
  console.log(`Fuzzy match candidates: ${fuzzy.length} (listed above, not inserted)`);
  console.log(`Missing: ${missing.length} (listed above)`);
  console.log();
  console.log(`Existing allowlist rows after run: ${totalExisting}`);
  for (const [county, cnt] of Object.entries(existingCounts)) {
    console.log(`  ${county}: ${cnt}`);
  }
  console.log();
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
